### ISSUE TITLE
About separating lexer and grammar, and make it work with debugger...

### ISSUE THREAD

**Issue by jan-johansson-mr** [mike-lischke/vscode-antlr4#101]
Hi,
Thanks for an amazing debugging tool with visualization!

I've separated the lexer and parser into two separate files, but I can't make it work with the debugger! If I build (I'm targeting C#, as a side note), then wire the lexer and grammar up and run as an app (on console) it works fine. But when I'm using the same lexer (file) and grammar (file) with the debugger, it doesn't work.

Is it possible to make this work with the debugger?

Thanks

**Comment by mike-lischke** [comment]
You cannot use the generated files for debugging. The extension uses the built-in interpreter, which uses the same prediction engine as the generated classes, but otherwise does a generic walk over the ATN for parsing in Javascript, which means it cannot handle side effects in your grammar (except fo predicates specifically set up for this debugging process, see also [grammar debugging](doc/grammar-debugging.md)).

**Comment by jan-johansson-mr** [comment]
Okay,

Thanks! What it means is that I'll simply break up the grammar in parts and
test it throughout before I wire everything together with compiled
artifacts.

It's easy to do, requires a little bit of tinkering :-)

Best!

Den tis 28 jan. 2020 08:55Mike Lischke <notifications@github.com> skrev:
