### ISSUE TITLE
Suggestion: use "antlr4.generation.language" for internal code generation

### ISSUE THREAD

**Issue by EternalPhane** [mike-lischke/vscode-antlr4#19]
It's possible that some rule names may conflict with generated code in target language, e.g. `operator` in C++, while they are valid identifier names in Java.

**Comment by mike-lischke** [comment]
The problem with that approach is that the Typescript target cannot produce the required interpreter data, hence it cannot be used for internal parser generation. We could do a fallback to any other language if `Typescript` is specified, but then we might be back to the original problem.

Now we could introduce another setting, just for internal generation, but that seems pretty odd, since this is something internal and hence per se not configurable by the user.
