### ISSUE TITLE
Documentation for setting up developer environment

### ISSUE THREAD

**Issue by mike-lischke** [mike-lischke/vscode-antlr4#203]
### Discussed in https://github.com/mike-lischke/vscode-antlr4/discussions/202

<div type='discussions-op-text'>

<sup>Originally posted by **chris-miner** February 19, 2023</sup>
I used to have a functional VSCode development environment for this project, but had to clean up some things on my development machine.  Anyway, I went looking for one of those project readme.md documents that so often include info about downloading the project, installing related tools, compiling, test running, installing, debugging, etc.  

Any pointers to such a document?</div>

**Comment by chris-miner** [comment]
Based on my recent experience the steps are rather straightforward:
1. install node
2. clone repository
3. npm install
4. launch extension

Maybe there should be an introductory paragraph about this being a vs code extension written in typescript.  Also something to explain why one's default theme changes in the launched host extension.  I don't have an answer to that.  I also wonder why source code is generated even though the settings for my sample project disable code generation.  I can't answer that either.

**Comment by mike-lischke** [comment]
Yes, there isn't much special handling required, beside generating the parser/lexer files for ANTLR4.

The other things you mentioned are rather bugs than something that should appear in a description about how to build and test the extension.

**Comment by chris-miner** [comment]
I haven't been able to verify that the theme and settings bit isn't the way a vs code extension is supposed to work.  Right now I'm leaning toward feature rather than bug.  

If I were developing a theme extension, then I'd probably find it annoying if my theme wasn't used by default when I launched the extension host.  Nice theme by the way.

Regarding the introductory paragraph, I will note that despite all the documentation on developing vs code extensions, it is not particularly useful.  So I was  thinking of summarizing the "obvious" bits about extensions or pointing to the docs for installing node or the docs for "your first vs code extension" even though I don't find the extension docs particularly helpful.

**Comment by mike-lischke** [comment]
I just added some documentation for setting up and debugging. I also tested the mode setting and it works for me as intended. Maybe you have a conflict with settings as user vs for the workspace? In any case this is worth a separate issue, if it persists.
