### ISSUE TITLE
syntax: cannot parsed v4-grammers/sql/tsql correctly

### ISSUE THREAD

**Issue by h3n4l** [mike-lischke/vscode-antlr4#215]
I download the `tsql` g4 parser files from [v4-grammers/sql/tsql](https://github.com/antlr/grammars-v4/tree/master/sql/tsql), but extension seems cannot parse it correctly:
<img width="1016" alt="CleanShot 2023-07-21 at 10 56 01@2x" src="https://github.com/mike-lischke/vscode-antlr4/assets/87714218/3b62cd61-f77a-4e66-8dbb-495d20e71102">

**Comment by mike-lischke** [comment]
Are you sure these diagnostics are produced from the ANTLR4 extension? What language is set for that file (check the status bar)?

**Comment by h3n4l** [comment]
Hi @mike-lischke , Sorry for the late : \
The language is  `ANTLR` exactly:
![image](https://github.com/mike-lischke/vscode-antlr4/assets/87714218/427b0157-86d5-4a67-b387-cdfe1fffb06c)

**Comment by mike-lischke** [comment]
OK, the problem stems from the fact that the TSQL grammar uses the new syntax already (ANTLR 4.12/13) with case insensitive identifiers. This ANTLR version is not yet supported by this extension, because I have no Typescript runtime for that. I'm working on one but it takes time. Once this is available I can improve the extension.

**Comment by mike-lischke** [comment]
A new release (2.4.0) was just published, which now works with the latest ANTLR4 version.
