### ISSUE TITLE
How to configure language generation settings

### ISSUE THREAD

**Issue by ChaseLewis** [mike-lischke/vscode-antlr4#33]
Trying to learn ANTLR and enjoying this extension greatly for debugging grammar. I'm getting to the point I'm wanting to start integrating the grammar into a project and while I see settings for configuring the language output, from the sparse documentation it is unclear to me how to configure the extension to output additional grammars (where should the setting file be placed in the folder & how . Is this possible or do I need to run the grammar through the command line? 

It would be nice if the builds were in the same project so that I can iterate between the without moving back & forth.

**Comment by mike-lischke** [comment]
The settings are stored by vscode and you don't need to take care to store a settings file somewhere. All you need to do is to specify an output folder (just like you would do when you run the ANTLR4 jar in a terminal). I recommend to use an absolute path to avoid having to figure how what the current dir is.

Once set the next generation run will write the new files into that output folder. It makes sense to use a folder in the project that uses the generated parser, so that you directly can compile it without further actions. The [readme](https://github.com/mike-lischke/vscode-antlr4/blob/master/README.md#extension-settings) file contains a list of all settings you can use. Look in particular at the `outputDir` setting.
