### ISSUE TITLE
Extension architecture design questions

### ISSUE THREAD

**Issue by cdietschrun** [mike-lischke/vscode-antlr4#71]
I'm trying to create a VSCode extension using webviews and found your extension which is excellent.

I've read through the code a lot last night and today and I have some questions, as I'm trying to port an Electron app I have into a VSCode extension, where the Electron app does nothing special with Electron and just uses yarn/npm packages inside some typescript/javascript files. In creating the HTML to open my webview, I use many third party libraries like request, jquery-ui, jquery, etc. With d3 in your example, you have it in your package.json, but also explicitly send d3 as a script url in the html? In other words, your node_modules that you depend on in your extension, are they ever used in the actual webviews? In my case, my webview uses and depends on through yarn/npm jQuery, request, bootstrap, and a few more, but they all have dependencies. I'm at the point where I'm able to send .js and .css files from my node_modules directory but then as they run and they have their own require statements, I get errors. It's not reasonable to add every .js that everything I rely on depends on in turn, so there's got to be a better way, but I don't see it right now.

Also in the example docs, they have the <meta http-equiv="Content-Security-Policy" > tag, do you not do that in your app? 

Thanks for any help and great work!

**Comment by mike-lischke** [comment]
The D3 dependency in package.json is a left over from earlier attempts. I wasn't sure if I can use the lib directly when I create the webview content. However, I developed the JS details for the extension visualizations in a standalone JS environment, where I needed the script import anyway. And I kept it that way.  You probably don't need the D3 node modules.

About the example docs question: I don't know what you mean with that. Which tag are you referring to?

**Comment by cdietschrun** [comment]
Thanks for the reply! My second question I think I meant to paste in something but it never pasted. I was referring to the 

<meta http-equiv="Content-Security-Policy" 

tag used in their example docs for the cat coding example, to control access to what types of resources are allowed. I don't see the use of that tag in your extension, is that by design?

And so if I follow your answer on the D3 dependency, you're saying I think what I'm finding with the webview, is that you weren't sure or were unable to use the npm packages being declared and able to be used in your typescript compiled classes/javascript, but when we reference scripts and modules in the webview, it doesn't understand them by default? Which seems to be a problem for my use case. I have lots of npm dependencies I want to use, all need to be inside the webview (as I'm really only trying to use VSCode as a base for extension's functionality and not really leverage anything else, unlike yours where you can leverage the language features of the VSCode editors). 

Does that make sense where I'm struggling? Do you have any advice for me trying to accomplish what I'm trying to do?

Thanks!

**Comment by mike-lischke** [comment]
Right, I haven't used the content security policy. I believe that wasn't recommended at the time I started the development of my webviews (previewHTML at that time). I only use `nonce`. However, I believe it's not a serious problem not to have that policy in place, if all you show is content you produce yourself.

Regarding D3 modules: my original plan was to create the HTML content from those modules, but later found it easier to write plain HTM with embedded JS. I have never tried to reference npm modules in webview and I believe that's not the way it should be used, but instead the module creates the actual HTML you can set in the webview. Not sure however, how mouse interaction is supposed to work, if you don't include D3.js in the generated HTML.

And I'm thinking since a while if it would be better to provide a local copy of D3.js, so that the webview doesn't need to access the internet (which might fail). That's not the node module, what I mean, but a copy of the minified original D3.js scripts.

**Comment by cdietschrun** [comment]
I think I understand what you're saying in all cases and it seems to line up with what I'm seeing. Basically, trying to move an Electron app into VSCode is a bit difficult unless I can think of some other way to include my npm dependencies in a smart way. 

Thanks for the great work!
