### ISSUE TITLE
Is it possible to add highlighting,diagnose,completion for file using .g4 grammer?

### ISSUE THREAD

**Issue by yafacex** [mike-lischke/vscode-antlr4#86]
Is it possible to auto add highlighting,diagnose,completion,hover,etc for the file using grammer defined in .g4 file?

**Comment by mike-lischke** [comment]
The vscode-antlr4 extension is designed to work only with ANTLR4 grammars. No other file type is supported.

**Comment by johnholliday** [comment]
I'd like to expand on what I believe @yafacex was asking.  Is it possible to enhance the extension so that in addition to the other artifacts it generates (e.g. parser for the language), it also generates files needed for syntax highlighting (perhaps a Textmate bundle or JSON file) in VSCode?

If this is not part of the roadmap, then can you suggest an approach that others could perhaps contribute to the project?

**Comment by mike-lischke** [comment]
Such files contain a lot of semantic information that cannot be read from a grammar (which is a syntactic description). How would you find out if a specific rule belongs to a specific syntactic element in a specific semantic context for a given IDE?

**Comment by johnholliday** [comment]
Agreed with respect to statement completion, but syntax highlighting is non-contextual and could be generated automatically.

**Comment by mike-lischke** [comment]
Comming back to this question as wonder what exactly is requested here, since I'm still not sure.

Syntax highlighting: How can this extension help here? Do you want a theme file for vscode generated during parser generation or something else?

Error diagnose: this feature in vscode is meant for the actual code (the code in an editor tab), not code that could be consumed by the actual code. So, I believe this not possible to accomplish.

Code completion: here is the biggest confusion for me. Code completion is done for code you enter, however in vscode this is done using registered code completion providers, which are registered for specific file types in an extension. Extensions cannot dynamically register other extensions, so I don't see what you are after here.
