### ISSUE TITLE
Lexer/Parser change iterations not detected by antlr-debug parseTree configuration option

### ISSUE THREAD

**Issue by iiian** [mike-lischke/vscode-antlr4#95]
I am running VSCode on macOS Mojave. The first time I debug my grammar using my launch target:
`{
            "type": "antlr-debug",
            "request": "launch",
            "name": "Debug Current Grammar",
            "input": "...",
            "grammar": "path/to/my/grammar.g4",
            "startRule": "rule",
            "visualParseTree": true
        }`

Whatever changes I might have made on the last save of `grammar.g4` are detected. Next my goal is to make an iterative change to `grammar.g4` and it's associated `lexer.g4`. I produce this change by running some scripts to update the output symbols of the grammar (via `java -jar /usr/local/lib/antlr-4.7.2-complete.jar -Dlanguage=JavaScript -visitor -no-listener path/to/my/grammar.g4` and the lexer equivalent `java -jar /usr/local/lib/antlr-4.7.2-complete.jar -Dlanguage=JavaScript path/to/my/lexer.g4`).

Then, finally, I try to run the debug target again, but it still matches the old rules. Is my debug session persisting too long? Is data being stored somewhere it shouldn't? I know there is the `.antlr` directory that gets autogenerated sometimes, but I'm frankly not sure fo the purpose upon investigating.

Thanks, Mike!

**Comment by mike-lischke** [comment]
In order to debug the grammar we need the interpreter data generated by ANTLR4. That must be in the internal folder used by the extension. If you enabled only internal generation then this happens automatically (as all output files are placed there). For external code generation the .interp file is explicitly moved to the internal folder, by the extension.

However, when you generate your parsers manually (e.g. with a script) then you have to do the move yourself too. For reference see the what the extension does [here](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/extension.ts#L324).

**Comment by iiian** [comment]
https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/parser-generation.md
I was unaware of this feature! Awesome. I think we can close this issue, @mike-lischke. Thanks for taking the time to help me be a little more knowledgeable :)
